import { APIGatewayProxyEvent } from 'aws-lambda';
import { EventBody } from '../types';

export const generateLambdaEvent = (bodyToStringify: EventBody): APIGatewayProxyEvent => ({
    body: JSON.stringify(bodyToStringify),
    headers: {
        'Content-Type': 'application/json',
    },
    httpMethod: 'POST',
    isBase64Encoded: false,
    multiValueHeaders: {},
    multiValueQueryStringParameters: null,
    path: '/hello',
    pathParameters: null,
    queryStringParameters: null,
    requestContext: {
        accountId: '123456789012',
        apiId: '1234567890',
        domainName: 'localhost:3000',
        extendedRequestId: undefined,
        authorizer: undefined,
        httpMethod: 'POST',
        identity: {
            accountId: null,
            apiKey: null,
            caller: null,
            cognitoAuthenticationProvider: null,
            cognitoAuthenticationType: null,
            cognitoIdentityPoolId: null,
            sourceIp: '127.0.0.1',
            user: null,
            userAgent: 'Custom User Agent String',
            userArn: null,
            accessKey: null,
            apiKeyId: null,
            clientCert: null,
            principalOrgId: null,
            cognitoIdentityId: null,
        },
        path: '/hello',
        protocol: 'HTTP/1.1',
        requestId: 'f68b0e88-329b-4a65-9e14-f5ddcaa8e09f',
        requestTimeEpoch: 1720797016,
        resourceId: '123456',
        resourcePath: '/hello',
        stage: 'dev',
    },
    resource: '/hello',
    stageVariables: null,
});
